#!/bin/bash -l
#SBATCH --account=rrg-aspuru
#SBATCH --time=24:00:00
#SBATCH --ntasks=192
#SBATCH -N 3
#SBATCH --mem=240GB
#SBATCH --exclusive
#SBATCH -c 1
#SBATCH -J r_janus

source ~/janus/bin/activate
source ~/xtb-6.5.0/share/xtb/config_env.bash

module load python/3.8
module load StdEnv/2020
module load gcc/9.3.0

module load openbabel/3.1.1
module load rdkit/2021.09.3
module load openmpi/4.0.3
module load mpi4py/3.1.3

export PATH=~/mopac/build:$PATH

srun python -u -m mpi4py.futures Click.py
